version: "3.9"

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 192.10.0.0/16

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=project_db
    networks:
      backend:
        ipv4_address: 192.10.1.1

  mysql:
    image: mysql
    container_name: mysql_db
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=project_db
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      backend:
        ipv4_address: 192.10.1.2

  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    networks:
      backend:
        ipv4_address: 192.10.1.3

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 27080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@mongo:27017
    networks:
      backend:
        ipv4_address: 192.10.1.4
    
  redis:
    image: redis:alpine
    container_name: redis_db
    ports:
      - 6379:6379
    container_name: redis
    networks:
      backend:
        ipv4_address: 192.10.1.5
  
  rabbitmq:
    build: ./docker/rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - 15672:15672
    networks:
      backend:
        ipv4_address: 192.10.1.6
